### ISSUE TITLE
Couldn't locate the included file

### ISSUE THREAD

**Issue by JulianOestreich90** [clnhlzmn/blog#1]
I wanted to try out your Gallery Plugin and followed your steps. My project didn't had a _config.yml so far and i created one with the content you suggested. Anyway i am getting this error when building my jekyll page.

`Liquid Exception: Could not locate the included file 'test.html' in any of ["/home/*/*/*/*/blog/_includes", "/home/*/.local/share/gem/ruby/3.0.0/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in gallery.html`

My _config.yml:
```
exclude:
  - test/

plugins:
  - jekyll-pig 

safe: true 

whitelist:
  - jekyll-pig

galleries:
    -
        path: test
        name: test 
```
And the gallery.html:
```
---
layout: default
title: Gallery
---

<div id="fgefe">
  <h1>Gallery</h1>
  {% include test.html %}
</div>
```
